[tools]
# Infrastructure as Code
opentofu = "1.8.8"
tflint = "0.50.3"

# AWS Tools
awscli = "2.22.21"

# Security Tools
"1password-cli" = "2.30.3"

# Python Development
python = "3.12"
ruff = "0.1.9"
black = "23.12.1"

# Shell Linting
shellcheck = "0.9.0"

# Utilities
jq = "1.7.1"
node = "20.18.0"
task = "3.38.0"

[env]
# Add scripts directory to PATH
_.path = ["./scripts"]

[settings]
# Automatically install tools when entering directory
experimental = true