---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart node_exporter
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
